destroy_users_job:
  cron: "0 0 * * *"
  class: "DestroyUsersJob"
  queue: destroy_users_job

sync_anime_job:
  cron: "0 0 * * *"
  class: "SyncAnimeJob"
  queue: sync_anime_job

hourly_unfilled_job:
  cron: 0 */6 * * *
  class: "HourlyUnfilledJob"
  queue: hourly_unfilled_job

event_reminder_job:
  cron: 0 * * * *
  class: "EventReminderJob"
  queue: event_reminder_job